# Specify our base image
FROM node:16-alpine

# Specify the working dir for our application inside the container
WORKDIR /usr/frontend/

# Copy the node server dependencies
COPY ./package.json /usr/frontend/

# Install node server
RUN npm install

# Copy the remaining source code
COPY ./ /usr/frontend/

# Start our node server
CMD [ "npm", "run", "start" ]