name: Build and Push frontend app to Docker Hub

on:
  push:
    branches:
      - 
        none # "main"
  pull_request:
    branches:
      -
        none # "main"

# Allows you to run this workflow manually from Actions tab
  workflow_dispatch:

jobs:
  build_push_docker_hub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: alexjdevil/frontend:latest 

# Introduction to GitHub Actions
# https://docs.docker.com/build/ci/github-actions/

# Checkout Action
# https://github.com/actions/checkout

# Docker Hub login Action
# https://github.com/docker/login-action

# Docker build and push Action
# https://github.com/docker/build-push-action

# Docker setup buildx
# https://github.com/docker/setup-buildx-action