name: Build and Test frontend app

on:
  push:
    branches:
      - 
        none # "main"
  pull_request:
      branches: 
      - 
        none # "main"

# Allows you to run this workflow manually from Actions tab
  workflow_dispatch:

jobs:
  build_run_tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout first
        uses: actions/checkout@v3
      -
        name: Build the image with Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.dev 
          push: false
          tags: alexjdevil/frontend-dev:latest
      -
        name: Run the image with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: alexjdevil/frontend-dev:latest
          run: npm run test

# Introduction to GitHub Actions
# https://docs.docker.com/build/ci/github-actions/

# Checkout Action
# https://github.com/actions/checkout

# Docker Hub login Action
# https://github.com/docker/login-action

# Docker setup buildx
# https://github.com/docker/setup-buildx-action

# Docker build and push Action
# https://github.com/docker/build-push-action

# Run a Docker container
# https://github.com/addnab/docker-run-action

# npm run test never finishes
# Add in package.json 
# Linux and Mac: "test": "CI=true react-scripts test -env=jsdom",
# Windows: "test": "set CI=true &&react-scripts test -env=jsdom", 
# https://github.com/facebook/create-react-app/issues/1137

# Using Docker Run inside GitHub Actions
# https://aschmelyun.com/blog/using-docker-run-inside-of-github-actions/#:~:text=So%2C%20you're%20able%20to,them%20one%20of%20two%20ways.&text=This%20first%20option%20is%20as%20the%20base%20for%20an%20entire%20job.